### ISSUE TITLE
Events are not visible on greyed-out days beyond the end of the current month

### ISSUE THREAD

**Issue by HALtheWise** [olin-build/abe-web#260]
When viewing the month view, no events show past the end of the current month, even when that day is visible on the calendar because it is part of the same row. This creates the false impression that nothing is happening then, and is different from how other calendar applications handle this case.

**Comment by kylecombes** [comment]
This is likely caused by the fact that the events are only fetched for the month being shown (at least on initial load). We need to make sure we fetch the events for all the dates that will be shown on the screen in [`refreshEvents` in `actions.js`](https://github.com/olin-build/abe-web/blob/299c983e4cde3e36c4d598e88b8b2b9d161e2d99/src/data/actions.js#L314).

Suggested change: increase the start and end dates sent in the URL to the server to include all the visible dates.

Relevant libraries:
* [Redux](https://redux.js.org/basics/basic-tutorial) (application state)
* [Moment.js](https://momentjs.com/docs/#/manipulating/) (date library)
